services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remessas-app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: remessas-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=remessas
      - MYSQL_USER=remessas
      - MYSQL_PASSWORD=remessas
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5
    container_name: remessas-pma
    environment:
      - PMA_HOST=db
      - PMA_USER=remessas
      - PMA_PASSWORD=remessas
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
